[package]
name = "wb-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
structopt = "0.3"
serde_json = "1.0"
rand = "0.8"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"
